# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package -Denforcer.fail=false --file pom.xml
    - name: Build & Publish Image
      run: echo Build Image   

  deploydev:
    needs: [mend-sast, mend-cli]
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: Deploy Development
        run: echo app deployed en dev
     
  deploypre:
    needs: deploydev
    runs-on: ubuntu-latest
    environment: preprod
    steps:
      - name: Deploy PRE
        run: echo app deployed en PRE

  deploypro:
    needs: deploypre
    runs-on: ubuntu-latest
    environment: prd
    steps:
      - name: Deploy PRO
        run: echo app deployed en PRO

  mend-sast:
     runs-on: ubuntu-latest
     needs: build
     env:
       MEND_SAST_API_TOKEN: e8240a7cc63e08109ce064d5b3f3dadf60c8d107a613061f727adc25d700a2c6
       MEND_SAST_SERVER_URL:  https://saas-eu.mend.io/sast
     steps:
       - name: Checkout repository
         uses: actions/checkout@v2
       # Download CLI
       - name: Download CLI
         run: curl -LJO https://downloads-sast.mend.io/sast-cli/linux/mendsastcli && chmod +x mendsastcli
       # Run CLI
       - name: Run Mend-SAST
         run: ./mendsastcli --dir ./ --name=${{github.event.repository.name}}-${{github.ref_name}}-${{github.sha}} --app=${{github.event.repository.name}} --baseline=true  
         
  mend-cli:
     needs: build
     env:
       MEND_EMAIL: juan.a.mora@accenture.com
       MEND_USER_KEY: 5997298ed7f5489e88b72ecd7d31662034cf25d221364cf8906a00deba127511
       MEND_URL: https://saas-eu.mend.io/
     runs-on: ubuntu-latest
     steps:
      # Downloading Mend CLI
       - name: Mend CLI
         run: | 
           echo Downloading Mend CLI
           curl https://downloads.mend.io/production/unified/latest/linux_amd64/mend -o /usr/local/bin/mend && chmod +x /usr/local/bin/mend
           echo Start Mend Container scan
           mend image juananmora/camas:30   
